global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Text;
global using System.Threading.Tasks;
global using FluentValidation;
global using Roman.CQRS.Abstraction.Query;
global using Roman.CQRS.Abstraction.Result;